# 一、函数对象和实例对象

## 1、函数对象

- 将函数作为对象使用时，简称函数对象

## 2、实例对象

- new函数产生的对象，简称为对象

## 3、区别函数和对象

- 函数（）:（）前面是函数
- 对象. ：.前面是对象

## 4、区别函数对象和实例对象

```javascript
function Fn(){}              // Fn函数
const fn = new Fn()          // Fn是构造函数（new） ；fn是实例函数（简称为对象）
console.log(Fn.prototype)    // Fn是函数对象
Fn.call({})                  // Fn是函数对象
```



# 二、回调函数的分类

## 1、回调函数

一个回调函数满足三个条件：

- 是自己定义的函数
- 自己没有调用它，但是却被执行的函数
- 被系统的函数当作参数执行了这个函数

## 2、同步回调

```javascript
const arr = [1,4,5]
arr.forEach(item=>{         //遍历回调，同步回调函数，不会放入列队，一上来就执行完
    console.log(item)
})
console.log('forEach()之后')
```

执行结果：先打印`item`，后打印`'forEach()之后'`

## 3、异步回调

```javascript
setTimeout(()=>{            //异步回调函数，会放入列队中将来执行
    console.log('timeout callback')        
},0)
console.log('setTimeout()之后')
```

执行结果：先打印 `console.log('setTimeout()之后')`， 后打印`console.log('timeout callback')`

# 三、Js的error处理

## 1、常见的内置错误

- ###### Error：所有错误的父类型

- ###### ReferenceError ：引用的变量不存在

- ###### TypeError：数据类型不正确

```javascript
let b;
console.log(b.XXX);    //TypeError: Cannot read property 'XXX' of undefined
b = {};
b.XXX();               // TypeError: b.XXX is not a function
```

- ###### RangeError：数据值不在其所允许的范围内

```js
function fn(){
    fn()
}
fn()                   //RangeError: Maximum call stack size exceeded
```

- ###### SyntaxError：语法错误

## 2、错误处理

- ###### 捕获错误：try.....catch

  ```javascript
  try{
      let b;
      console.log(b.XXX);
  }catch(error){
      console.log(error.message);
      console.log(error.stack);
  }
  ```

- ######  抛出错误：throw new Error

  ```javascript
  function something(){
      if(Date.now()%2===1){
          console.log('当前时间为奇数，可以执行任务')
        }else{
            throw new Error('当前时间为偶数，无法执行任务')
        }  
  }
  try {
      something()
  }catch(error){
      alert(error.message)
  }
  
  ```

## 3、错误对象

- ###### message属性：错误的相关信息

  `Cannot read property 'XXX' of undefined`

- ###### stack属性：函数调用栈记录信息

​       `TypeError: Cannot read property 'XXX' of undefined`